name: Build

on:
  push:
    branches: [ "**" ]
  schedule:
   - cron: "1 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'gradle'
        
      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Set outputs
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Repository Name
        uses: MariachiBear/get-repo-name-action@v1.1.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.repo-name.outputs.repository-name }} ${{ steps.short_sha.outputs.sha_short }}
          path: build/libs/*.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.repo-name.outputs.repository-name }}
          tag_name: ${{ steps.short_sha.outputs.sha_short }}
          body: |
            This release is automatically compiled by GitHub Actions
          files: |
            build/libs/*.jar
          generate_release_notes: true
